import Link from "next/link"
import type { Metadata } from "next"
import { Button } from "@/components/ui/button"
import { ReportCard, reportData } from "@/components/report-card"

export const metadata: Metadata = {
  title: "Sample Report — Priya Field Intelligence",
  description:
    "A sample field visit debrief report generated by Priya, the AI voice agent for Indian pharma and FMCG teams.",
}

export default function SamplePage() {
  return (
    <div className="min-h-svh bg-background">
      <div className="max-w-3xl mx-auto px-4 py-12">
        {/* Back link */}
        <div className="mb-8">
          <Button asChild variant="ghost" size="sm" className="-ml-2">
            <Link href="/">← Back to Priya</Link>
          </Button>
        </div>

        {/* Header */}
        <div className="mb-8">
          <p className="text-xs font-semibold text-primary uppercase tracking-widest mb-2">
            Sample Report · Priya Field Intelligence
          </p>
          <h1 className="text-3xl md:text-4xl font-bold font-heading text-foreground mb-3">
            What your manager receives.
          </h1>
          <p className="text-muted-foreground">
            This report was generated automatically from a 116-second phone call
            in Hindi. No typing. No WhatsApp forwards. No delayed review
            meetings.
          </p>
        </div>

        {/* Report */}
        <ReportCard data={reportData} />

        {/* CTA */}
        <div className="mt-10 bg-card border border-border rounded-2xl px-6 py-8 text-center">
          <h2 className="text-xl font-bold font-heading text-foreground mb-2">
            Want to generate a real one?
          </h2>
          <p className="text-muted-foreground text-sm mb-5">
            Enter your number. Priya will call you and send a report like this
            to your inbox in under 2 minutes.
          </p>
          <Button asChild size="lg">
            <Link href="/#demo">Try it on yourself →</Link>
          </Button>
        </div>
      </div>
    </div>
  )
}
